#!/usr/bin/env python3
"""
Generate IIR biquad coefficients for the tremor bandpass filter.

Run this script once before building firmware:
    python3 generate_coeffs.py

Paste the output into firmware/src/filters.c at the BANDPASS_COEFFS array.

Filter spec:
  Type:  4th-order Butterworth bandpass
  Band:  3–8 Hz (rejects voluntary movement <2 Hz and noise >8 Hz)
  Fs:    200 Hz (IMU sample rate)

CMSIS-DSP Direct Form II Transposed coefficient order per stage:
  [b0, b1, b2, -a1, -a2]   (note: CMSIS stores negated feedback coefficients)
"""

import numpy as np
from scipy.signal import butter, sosfilt, freqz

FS     = 200.0
F_LOW  = 3.0
F_HIGH = 8.0
ORDER  = 4      # Butterworth order (produces ORDER/2 biquad stages per LP/HP)


def sos_to_cmsis(sos):
    """Convert scipy SOS matrix to CMSIS-DSP coefficient array.

    scipy SOS row: [b0, b1, b2, a0, a1, a2]  (a0 always 1.0 when normalised)
    CMSIS stage:   [b0, b1, b2, -a1, -a2]     (negated a1/a2, a0 implicit)
    """
    stages = []
    for row in sos:
        b0, b1, b2 = row[0], row[1], row[2]
        a0, a1, a2 = row[3], row[4], row[5]
        assert abs(a0 - 1.0) < 1e-9, "SOS not normalised"
        stages.append((b0, b1, b2, -a1, -a2))
    return stages


def print_c_array(stages):
    print(f"/* {ORDER}th-order Butterworth bandpass {F_LOW}–{F_HIGH} Hz @ {FS} Hz fs */")
    print(f"/* {len(stages)} biquad stages */")
    print(f"static const float BANDPASS_COEFFS[{len(stages)} * 5] = {{")
    for i, (b0, b1, b2, na1, na2) in enumerate(stages):
        print(f"    /* Stage {i} */ "
              f"{b0:+.10f}f, {b1:+.10f}f, {b2:+.10f}f, "
              f"{na1:+.10f}f, {na2:+.10f}f,")
    print("};")


def verify_response(sos):
    """Quick sanity check: print gain at key frequencies."""
    print("\n/* Frequency response verification:")
    for f in [0.5, 1.0, 3.0, 5.0, 8.0, 10.0, 20.0]:
        w = 2 * np.pi * f / FS
        _, h = freqz([1], [1], worN=[w])
        # evaluate manually through SOS
        n_pts = 1
        w_arr = np.array([w])
        z = np.exp(1j * w_arr)
        H = np.ones(n_pts, dtype=complex)
        for row in sos:
            b = row[:3]; a = row[3:]
            H *= (b[0] + b[1]/z + b[2]/z**2) / (a[0] + a[1]/z + a[2]/z**2)
        gain_db = 20 * np.log10(abs(H[0]) + 1e-12)
        print(f"    f={f:5.1f} Hz: {gain_db:+7.2f} dB")
    print("*/")


def main():
    sos = butter(ORDER, [F_LOW, F_HIGH], btype='bandpass', fs=FS, output='sos')
    stages = sos_to_cmsis(sos)

    print(f"// Auto-generated by generate_coeffs.py")
    print(f"// DO NOT EDIT — re-run the script to regenerate\n")
    print_c_array(stages)
    verify_response(sos)

    print(f"\n// Number of stages (for BANDPASS_NUM_STAGES in filters.h): {len(stages)}")


if __name__ == "__main__":
    main()
