#include "filters.h"
#include <string.h>
#include <math.h>

/* Biquad coefficients for a 4th-order Butterworth bandpass, 3–8 Hz @ 200 Hz fs.
   Generated by generate_coeffs.py.
   CMSIS-DSP format per stage: {b0, b1, b2, -a1, -a2}
   Run generate_coeffs.py and paste the output here before building. */
/* 4th-order Butterworth bandpass 3–8 Hz @ 200 Hz fs.
   Auto-generated by generate_coeffs.py — do not edit manually.
   CMSIS-DSP format per stage: {b0, b1, b2, -a1, -a2} */
static const float BANDPASS_COEFFS[BANDPASS_NUM_STAGES * 5] = {
    /* Stage 0 */ +0.0000312390f, +0.0000624780f, +0.0000312390f, +1.8043339469f, -0.8380003115f,
    /* Stage 1 */ +1.0000000000f, +2.0000000000f, +1.0000000000f, +1.8774675545f, -0.8919416397f,
    /* Stage 2 */ +1.0000000000f, -2.0000000000f, +1.0000000000f, +1.8609211429f, -0.9179251583f,
    /* Stage 3 */ +1.0000000000f, -2.0000000000f, +1.0000000000f, +1.9571144859f, -0.9663456674f,
};

#define COMP_ALPHA 0.96f

#ifndef NATIVE_TEST
/* On-target: use CMSIS-DSP arm_biquad_casd_df2T_f32 */
#include "arm_math.h"

static arm_biquad_casd_df2T_instance_f32 s_biquad_inst;

void filters_bandpass_init(BandpassFilter *f)
{
    memset(f->state, 0, sizeof(f->state));
    arm_biquad_casd_df2T_init_f32(&s_biquad_inst, BANDPASS_NUM_STAGES,
                                   (float32_t *)BANDPASS_COEFFS,
                                   (float32_t *)f->state);
}

float filters_bandpass_apply(BandpassFilter *f, float sample)
{
    (void)f; /* state owned by s_biquad_inst pointing into f->state */
    float32_t out;
    arm_biquad_casd_df2T_f32(&s_biquad_inst, &sample, &out, 1);
    return out;
}

#else
/* Native test build: plain C biquad cascade (same numerics, no CMSIS dependency) */

static void biquad_df2t(const float *coeffs, float *state,
                        float in, float *out)
{
    float b0 = coeffs[0], b1 = coeffs[1], b2 = coeffs[2];
    float a1 = coeffs[3], a2 = coeffs[4]; /* stored as -a1, -a2 in CMSIS convention */
    float w0 = in + a1 * state[0] + a2 * state[1];
    *out = b0 * w0 + b1 * state[0] + b2 * state[1];
    state[1] = state[0];
    state[0] = w0;
}

void filters_bandpass_init(BandpassFilter *f)
{
    memset(f->state, 0, sizeof(f->state));
}

float filters_bandpass_apply(BandpassFilter *f, float sample)
{
    float x = sample;
    for (int s = 0; s < BANDPASS_NUM_STAGES; s++) {
        float y;
        biquad_df2t(&BANDPASS_COEFFS[s * 5], &f->state[s * 2], x, &y);
        x = y;
    }
    return x;
}
#endif /* NATIVE_TEST */

void filters_comp_init(CompFilter *f)
{
    f->angle = 0.0f;
}

float filters_comp_update(CompFilter *f, float gyro_rate_rads,
                          float accel_angle, float dt)
{
    f->angle = COMP_ALPHA * (f->angle + gyro_rate_rads * dt)
             + (1.0f - COMP_ALPHA) * accel_angle;
    return f->angle;
}
